### ISSUE TITLE
🐫5⃣ Meta-issue for OCaml 5 support

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#330]
cooltt itself is ready for the current OCaml 5, but some of its dependencies need to be updated:

- [ ] [iter](https://github.com/c-cube/iter) (changes merged, but not published yet)
  ```sh
  opam pin git+https://github.com/c-cube/iter.git
  ```
- [ ] https://github.com/janestreet/sexplib0/pull/7
  ```sh
  opam pin git+https://github.com/kit-ty-kate/sexplib0.git#500-014
  ```
- [x] https://github.com/c-cube/ocaml-containers/issues/405 (published)
- [ ] https://github.com/ocaml-doc/odoc-parser/pull/6
  ```sh
  opam pin git+https://git@github.com/talex5/odoc-parser.git#stream-5.0
  ```
- [ ] https://github.com/ocaml/odoc/pull/831
  ```sh
  opam pin git+https://github.com/kit-ty-kate/odoc.git#500
  ```

One can manually pin these PRs for the moment.

**Comment by c-cube** [comment]
If `iter`'s master branch works, I'll cut a release soon ish, I think.
