### ISSUE TITLE
🥡 [Meta] Turn components into reusable modules

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#332]
To speed up the development of the next generation of cooltt, I propose turning isolated components into more OCaml packages ~~with anime-inspired names~~. Here are some ideas:

- [x] Namespaces: [yuujinchou](https://github.com/RedPRL/yuujinchou)
  - [ ] Scopes: moved to [yuujinchou](https://github.com/RedPRL/yuujinchou)
- [x] Unit resolution: [bantorra](https://github.com/RedPRL/bantorra)
- [ ] Pretty printing with precedence
- [ ] Cofibration
- [ ] Persistent union and find
- [ ] Bwd
- [ ] Universe levels
- [ ] Visualization
