### ISSUE TITLE
Grammar 🧞 in service

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/cooltt#69]
Following #44, let's accumulate more items here. Don't close this issue immediately if you fix the first problem. :smile: 

- [x] Need to write `k=0 ∨ {∂ i}` instead of `k=0 ∨ ∂ i` (done by #70 and #63)
- [x] Allow `i=0 ∨ j=0 ∨ k=0` (done by #73)
- [x] Omit the lambda symbol (done by #92)
- [ ] Allow n-ary tuples (but then we have to decide what `[ a => b ]` means)
- [x] Drop the parens around type annotations, and change the operator to `:` (#94 and then partially reverted by #105)
- ~`fst x y` should be parsed as `fst x y`. So do `snd`, `vproj`, and `cap`.~

**Comment by favonia** [comment]
Okay I can be the genie (working from home, not in the bottle).

**Comment by favonia** [comment]
@cangiuli @jonsterling How do you want to parse `i=0 \/ j=0 /\ k=0`?

**Comment by favonia** [comment]
@jonsterling @cangiuli For the typing annotation... how about
```
M : A
```
and then `A @ [ phi -> blah ]` for cubical subtyping? Why do we want parens around a typing annotation?

**Comment by jonsterling** [comment]
I don't know what you're talking about with parentheses. We don't even have typing annotations in the grammar currently.

**Comment by jonsterling** [comment]
Oh LOL never mind, you're right --- we do!

**Comment by jonsterling** [comment]
@favonia  The answer to virtually every question of the form "Why did we write the grammar to be like XXX?" will be "Because Jon has zero interest in spending hours and hours figuring out how to parse the immortal notation, but you should feel free to do so."

I don't like the cool notation for cubical subtype, because in practice it will look pretty gnarly; a concrete example is:

    A @ [ (i=0 \/ i=1) -> [i=0 -> foo | i=1 -> bar] ]

I think this rather beats the point of a cool notation. And I do not want to try and guess the cofibration from the partial element, because generally speaking there is no reason to believe that there will be a split at the top level (or, if there is, that this evinces the right cofibration).

**Comment by favonia** [comment]
I see. But how do you feel between `M : A` and `M @ A`?

**Comment by favonia** [comment]
Also I want to know how you feel about `x => M : A`. Is that annotating the entire function or just the body? @cangiuli

**Comment by jonsterling** [comment]
> Also I want to know how you feel about `x => M : A`. Is that annotating the entire function or just the body? @cangiuli

This one should clearly be annotating the body. Function abstraction associates _forever_.

**Comment by favonia** [comment]
> > Also I want to know how you feel about `x => M : A`. Is that annotating the entire function or just the body? @cangiuli
> 
> This one should clearly be annotating the body. Function abstraction associates _forever_.

Your wish will be granted. LOL

**Comment by jonsterling** [comment]
> I see. But how do you feel between `M : A` and `M @ A`?

I have no preference; the first is more familiar, but harder to parse.

**Comment by favonia** [comment]
> > I see. But how do you feel between `M : A` and `M @ A`?
> 
> I have no preference; the first is more familiar, but harder to parse.

Difficulty is not a concern unless it is mathematically impossible... I should add that there's actually a mechanical way to calculate all of these. Perhaps one should write menhir++ to automate the calculation in my mind.

**Comment by jonsterling** [comment]
Actually, I feel that difficulty should be a concern. I realize you're the "genie", but I am the "maintainer" so having you do totally nutty things to the parser is not responsible on my part. So, I need you to use your judgment as to whether supporting something is actually a good idea, or if it will make the code impossible to maintain.

(I don't think `@` vs `:` is an example of something that is so hard that it makes me concerned; I just want to nip in the bud the idea that we will be doing totally crazy things in the parser just because @favonia has grasped the geometry of Menhir lol)

**Comment by favonia** [comment]
Alright. You can always check the parser after I apply the Magic. LOL

**Comment by favonia** [comment]
Some oddity:
```
let x : A : B : C : D = M
```
would be parsed as
```
let x : (((A : B) : C) : D) = M
```

**Comment by favonia** [comment]
@jonsterling @cangiuli What was the discussion about `{}` and `()`? Parens are only used in telescopes.

**Comment by jonsterling** [comment]
Re: `{}/()`, I like it as it is --- that is, `{}` should be used for grouping, and `()` can be used for other stuff.

**Comment by favonia** [comment]
It's me again. What should be the syntax of `V` types and `VProj`? Not sure about `V`. Here is the proposal:
```
V a b e
vproj e
```

**Comment by favonia** [comment]
@clayrat @jonsterling @cangiuli I need more specs about the Wish. How about `fst fst x`? Should it be...

1. an error, or
2. `fst {fst x}`?

**Comment by jonsterling** [comment]
@favonia My specification is "fst should be like any function".

**Comment by favonia** [comment]
> @favonia My specification is "fst should be like any function".

This would means `{fst fst} x`, then.

**Comment by jonsterling** [comment]
OK lmao, my new specification is "It should work like Agda" lmao. 😉  I think I don't want to answer your specific questions, because there is a very clear "obviously correct" grammar, and I feel that I will be easily trapped by answering specific questions wrongly (be careful what I wish for!) when the 🧞 can guess what I mean 🤣

**Comment by favonia** [comment]
@jonsterling Okay. just FYI, OCaml developers made a different Wish about their pattern language some time ago...

**Comment by favonia** [comment]
We could re-introduce the `.fst` postfix notation from a project long time ago. ;-)

**Comment by jonsterling** [comment]
Hahahahaha :) I liked that notation but everyone revolted against me in such brain-damaged ways, I am hesitant to re-introduce it. lol

**Comment by RobertHarper** [comment]
I myself like .1, .2, etc.  Short and to the point.  And for injections 1., 2., etc.  (The dots would be \cdot’s.)



(c) Robert Harper  All Rights Reserved.
